# Generated by Django 3.2.19 on 2023-05-14 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondbconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessiondbconfiguration',
            name='session_key',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='NaturalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nl_query', models.TextField(null=True)),
                ('sql_query', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.sessiondbconfiguration')),
            ],
        ),
    ]
